### PR TITLE
Use spring boot to refactor elastic-job-lite-console

### LINKED ISSUE #836: Use spring boot to refactor elastic-job-lite-console
The current elastic-job-lite-console is using jetty.

For convenient reason, it is better to change it to spring boot.
After change to spring boot, we need use it to handle job event dao with spring boot + JPA.

### PR DESCRIPTION
**Pull request by kekerzzZ**
Fixes #836.

Changes proposed in this pull request:
Use spring boot to refactor elastic-job-lite-console.

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
Can you fix the CI?

**Comment by terrymanu** [comment]
The CI failure is caused by the new banner file which do not include apache copyright, can you add them or just remove the banner file?

**Comment by kekerzzZ** [comment]
ok. i fix it.

**Comment by kekerzzZ** [comment]
@terrymanu 
I created a new file, but rat warning Files with unapproved licenses.  how can I solve it?

**Review by TeslaCN — CHANGES_REQUESTED** [review]
New files are missing ASF license header.

**Comment by kekerzzZ** [comment]
@TeslaCN  
thanks.

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
