### PR TITLE
fix Issue 2429

### LINKED ISSUE #2429: 失效转移导致job不在执行
### Which version of ElasticJob did you use?
3.0.3

服务器A 和服务器B （服务器A和B 至少保证一个是在线状态）
服务器A运行job分片0  服务器B运行job分片1
操作：step:1 job 分片0和1 正在running，停止并启动服务器B，此时job 分片1的任务会转移在服务器A上执行。
          step2:等待服务器B启动成功，此时服务器A上正在运行失效转移的job分片1，或者还未运行，此时服务器A再次启停

### Expected behavior
job 到点能够正常触发
### Actual behavior
job 不在触发，几乎是必现
### Reason analyze (If you can)
zk节点查看状态
image

分片1 的节点 failover  和failovering 及running 状态一直存在，一直未清除导致job 不再执行。
应该是停止服务器A的时候，代码还没有走到清除failovering的那里，导致节点一直在
当step2 中服务器A启动的时候，LegacyCrashedRunningItemListener 无法做监听操作，因为一直会有两个实例在，代码bu hui qu不会去做失效转移相关操作，导致节点一直在
image

### PR DESCRIPTION
**Pull request by wjdxw**
Fixes #2429.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Review by linghengqian — COMMENTED** [review]
- The PR did not pass the code formatting validation. You can execute first `./mvnw spotless:apply -Pcheck -T1C`. Then execute `./mvnw checkstyle:check -Pcheck -T1C` to manually adjust to repair the CI.

**Comment by wjdxw** [comment]
Hello, the code has been updated. Only modified the code that caused the second issue mentioned earlier.

**Comment by wjdxw** [comment]
Hello, the code has been updated. Only modified the code that caused the second issue mentioned earlier.

**Review by linghengqian — APPROVED** [review]
LGTM!

**Pull request merged**
