### PR TITLE
为了兼容一些开源框架的升级，升级elastic-job所一些版本的依赖

### PR DESCRIPTION
**Pull request by dragontree101**
Changes proposed in this pull request:
-  由于项目使用了springboot2进行了集成，springboot2升级了很多依赖的版本，如果elastic-job不进行相关依赖的升级， 会导致版本的不兼容和冲突。所以升级了一些依赖版本
- 升级了使用的jdk的版本，现在jdk1.8已经是主流，spring5 和 springboot2 也只支持 jdk1.8了，所以升级了jdk的版本

### CODE REVIEW

**Comment by terrymanu** [comment]
we cannot just upgrade version without reason. please provide your reason for upgrade for each lib

**Comment by dragontree101** [comment]
spring5 和 springboot2 只支持 jdk1.8了 ， 希望elasticjob也能升级到jdk1.8来，然后elasticjob依赖了curator, springboot统一管理了curator的版本， 并且进行了升级， 导致elasticjob依赖的curator和springboot2 管理的curator 版本不兼容，所以希望进行升级

**Comment by terrymanu** [comment]
elasticjob based on jdk7, so it can use on jdk8 also, do not need upgrade jdk version

**Comment by terrymanu** [comment]
upgrade curator maybe cause original zookeeper cannot use any more, so we need to research them, which version of zookeeper cannot supported any more

**Comment by m1ngyuan** [comment]
If you want to work with spring boot 2.x, you have to do two things.

1. Due to the use of non recommended methods(MoreExecutors.sameThreadExecutor) in class org.apache.curator.framework.listen.ListenerContainer；You can look at the related issue,
 https://github.com/apache/curator/pull/240 ,Please rewrite it,you can work with guava 23

2. upgrade  org.springframework:spring-expression from 4.3.X.RELEASE to 5.0.X.RELEASE

**ENJOY!!!**

**Comment by terrymanu** [comment]
ElasticJob will as a subproject of Apache ShardingSphere soon, we will change the package and artifactId.
I just close too old pull request for now.

**Pull request closed without merging**
