### PR TITLE
Update GsonFactoryTest.java

### PR DESCRIPTION
**Pull request by y553546436**
Remove potential test order dependency

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
Hi @y553546436 ,

I can't get your point. Could you clarify what the problem is?

**Comment by y553546436** [comment]
> Hi @y553546436 ,
> 
> I can't get your point. Could you clarify what the problem is?

Hi @TeslaCN, this test modifies GsonFactory, which contains (static) fields shared among tests. If other tests are added later on which assume the default behavior of GsonFactory, they would fail. In another word, this test "pollutes" the shared program state and could potentially lead other tests run after it to fail. Though there is no severe problem now, it would be good to clean the state (remove the "pollution") at the end of the test.

**Comment by TeslaCN** [comment]
Hi @y553546436 ,

I see what you mean now. But on the one hand, register another TypeAdapter cannot eliminate the impact, unless you remove the registered TypeAdapter from GsonBuilder. On the other hand, `GsonFactoryTest` is just a simple unit test class should not be used by other testcase.

**Comment by TeslaCN** [comment]
Close due to no response.

**Comment by y553546436** [comment]
Sorry that I didn't follow up because I did not receive the notification email from GitHub. 
Indeed, this PR is of poor quality because (1) it lacks good description, (2) it does not follow your PR template (one PR points to one issue), and (3) the code does not fully remove the pollution, as you have commented.
I sincerely apologize for my carelessness, and have opened a new PR that addresses the above three issues: #1901.

**Pull request closed without merging**
