### PR TITLE
Use spring boot + JPA to deal with search dao

### LINKED ISSUE #837: Use spring boot + JPA to deal with search dao
Current search dao is using JDBC which can not adapt different database dialects.
It is better to use spring boot + JPA to more databases.

### PR DESCRIPTION
**Pull request by viviel**
Fixes #837.

Changes proposed in this pull request:
- refactor search dao with spring boot jpa

### CODE REVIEW

**Comment by Technoboy-** [comment]
Hi @viviel,
Some test cases are not passed. please check!

**Comment by viviel** [comment]
Oh, thank you. I'll see what's wrong

**Review by terrymanu — CHANGES_REQUESTED** [review]
Could you fix the CI？

**Comment by viviel** [comment]
OK, it's being fixed

**Review by terrymanu — APPROVED** [review]

**Pull request merged**
