### PR TITLE
adjust spring module structure

### LINKED ISSUE #1116: Adjust spring module structure
The current spring module structure is not good enough after we add the spring boot starter module.
The current structure is:

```
--elasticjob-lite-spring
--elasticjob-lite-spring-boot-starter
```

How about adjust them to:

```
--elasticjob-lite-spring
----elasticjob-lite-spring-boot-starter
----elasticjob-lite-spring-namespace
```

***It is better to adjust example modules too.***

### PR DESCRIPTION
**Pull request by cocodroid**
Fixes #1116.

### CODE REVIEW

**Review by terrymanu — CHANGES_REQUESTED** [review]
The pom is not correct,
The parent pom of spring boot starter and spring namespace should be elasticjob-lite-spring, not elasticjob-lite

**Comment by terrymanu** [comment]
@cocodroid  The pr has conflicted, can you resolve them?

**Comment by cocodroid** [comment]
@terrymanu I try resolve it

**Comment by terrymanu** [comment]
@cocodroid The pr is broken the travis, please fix it

**Review by terrymanu — APPROVED** [review]

**Review by terrymanu — APPROVED** [review]

**Comment by terrymanu** [comment]
Sorry, I need to revert this pr, because this pr do not move the spring boot's test cases

**Pull request merged**
