### PR TITLE
[ISSUE #2110] Support legacy version Zookeeper as registry center

### LINKED ISSUE #2110: [Feature] Support low version zookeeper as registry center
## Feature Request
Support low version zookeeper as registry center.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
Yes.

### Describe the feature you would like.
There is a version mapping relationship between the popular Zookeeper client Curator and Zookeeper,  so the current Zookeeper registry plugin does not support lower versions of Zookeeper.  But because of some overall considerations, some companies are still using lower versions of zookeeper, so I hope to rely on the lower version of Curator to implement a new Zookeeper registry plugin to support the lower version of Zookeeper.

### PR DESCRIPTION
**Pull request by mytang0**
Fixes #2110 .

Changes proposed in this pull request:
- Support  legacy version Zookeeper as registry center.

### CODE REVIEW

**Comment by TeslaCN** [comment]
Hi @mytang0 
Thanks for your contribution. Actually I want to discuss about reusing [ShardingSphere's cluster mode](https://github.com/apache/shardingsphere/tree/master/shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository) in ElasticJob. Maintaining similar codes in sub-project will disperse developers' energies. You may [start a discussion](https://shardingsphere.apache.org/community/en/contribute/subscribe/) about supporting legacy version Curator in ShardingSphere Cluster mode. What do you think?

**Comment by mytang0** [comment]
> Hi @mytang0 Thanks for your contribution. Actually I want to discuss about reusing [ShardingSphere's cluster mode](https://github.com/apache/shardingsphere/tree/master/shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository) in ElasticJob. Maintaining similar codes in sub-project will disperse developers' energies. You may [start a discussion](https://shardingsphere.apache.org/community/en/contribute/subscribe/) about supporting legacy version Curator in ShardingSphere Cluster mode. What do you think?

**Comment by mytang0** [comment]
> Hi @mytang0 Thanks for your contribution. Actually I want to discuss about reusing [ShardingSphere's cluster mode](https://github.com/apache/shardingsphere/tree/master/shardingsphere-mode/shardingsphere-mode-type/shardingsphere-cluster-mode/shardingsphere-cluster-mode-repository) in ElasticJob. Maintaining similar codes in sub-project will disperse developers' energies. You may [start a discussion](https://shardingsphere.apache.org/community/en/contribute/subscribe/) about supporting legacy version Curator in ShardingSphere Cluster mode. What do you think?

Ok.

**Comment by SuperCarrys** [comment]
There is no standardized result before this problem target, such as how the low version of zk uses the 3.x version of elasticjob

**Pull request closed without merging**
