### PR TITLE
Enhance Dump Job

### LINKED ISSUE #2047: Enhance Dump Job
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
1）if use elasticjob-lite, you can directly call SnapshotService#dumpJobDirectly to dump job. Some requirements may require direct exposure to the application.
2)  In other scenarios, SnapshotService#dumpJob may be used to call other job service nodes to obtain Dump job information.For Example Admin Console,and so on. see #https://github.com/apache/shardingsphere-elasticjob-ui/issues/147
3) Support API(JobOperateAPI#dump:(jobName, instanceIp, dumpPort)) to dump job.

### PR DESCRIPTION
**Pull request by cocodroid**
Fixes #2047.

Changes proposed in this pull request:
1）if use elasticjob-lite, you can directly call SnapshotService#dumpJobDirectly to dump job. Some requirements may require direct exposure to the application.
2) In other scenarios, SnapshotService#dumpJob may be used to call other job service nodes to obtain Dump job information.For Example Admin Console,and so on. see #apache/shardingsphere-elasticjob-ui#147
3) Support API(JobOperateAPI#dump:(jobName, instanceIp, dumpPort)) to dump job.

### CODE REVIEW

**Comment by TeslaCN** [comment]
Hi @cocodroid 
The CI failed. Could you have a look?

**Comment by cocodroid** [comment]
@TeslaCN I have try resolve it, but it also failed. Can you help me to look?

**Comment by cocodroid** [comment]
> Hi @cocodroid 
> The CI failed. Could you have a look?

It's done.

**Review by TeslaCN — APPROVED** [review]
Thank you @cocodroid !

**Pull request merged**
