### PR TITLE
Make sure supporting the case that job instances are crashed while ex…

### LINKED ISSUE #1868: I can't find the branch which includes the code from Bug fix for Failover #714
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere-elasticjob/issues).
- Read documentation: [ElasticJob Doc](https://shardingsphere.apache.org/elasticjob/current/en/overview/).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

image

Hi，Bug fix for Failover #714  merged into  apache:3.0 branch，but   I  can't find  the apache:3.0 branch

And I can't find the code from Bug fix for Failover #714 in the master branch.

So, I'd like to find which branch includes the code from Bug fix for Failover #714, thx~

### PR DESCRIPTION
**Pull request by sucg**
Make sure supporting the case that job instances are crashed while executing failover.

Fixes #1868.

Changes proposed in this pull request:

Bugfix for Failover

Bugfix for Failover #714 is missing, submit a new PR.

### CODE REVIEW

**Comment by TeslaCN** [comment]
Hi @sucg 
Thanks for your contribution! Before merging this PR, I'll make some tests about failover.

**Comment by TeslaCN** [comment]
I deployed 3 nodes in Docker. Killed one when the job was running. But NPE occurred and the failover didn't worked. Did I missed something?

My Job:
```java
@Slf4j
public final class FailoverMain {

    private static final CoordinatorRegistryCenter REGISTRY_CENTER = Configurations.getCoordinatorRegistryCenter();

    private static final int SLEEP_SECONDS = 20;

    public static void main(final String[] args) {
        SimpleJob job = shardingContext -> {
            log.info("Start {}", shardingContext);
            for (int i = 0; i < SLEEP_SECONDS; i++) {
                try {
                    Thread.sleep(1000);
                    log.info("Handling {}", shardingContext.getShardingItem());
                } catch (final InterruptedException ex) {
                    Thread.currentThread().interrupt();
                    ex.printStackTrace();
                }
            }
            log.info("Done {}", shardingContext);
        };
        new ScheduleJobBootstrap(REGISTRY_CENTER, job, jobConfiguration()).schedule();
    }

    private static JobConfiguration jobConfiguration() {
        return JobConfiguration.newBuilder("failover-job", 3)
                .cron("0 * * * * ?")
                .jobErrorHandlerType("LOG")
                .monitorExecution(false)
                .overwrite(true)
                .failover(true)
                .maxTimeDiffSeconds(1)
                .addExtraConfigurations(Configurations.getTracingConfiguration())
                .build();
    }
}
```

```
02:27:08.871 [Curator-SafeNotifyService-0] ERROR org.apache.curator.framework.listen.MappingListenerManager - Listener (org.apache.shardingsphere.elasticjob.lite.internal.failover.FailoverListenerManager$JobCrashedJobListener@698122b2) threw an exception
java.lang.NullPointerException: null
	at java.io.StringReader.<init>(StringReader.java:50) ~[?:1.8.0_275]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:63) ~[snakeyaml-1.26.jar:?]
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:452) ~[snakeyaml-1.26.jar:?]
	at org.apache.shardingsphere.elasticjob.infra.yaml.YamlEngine.unmarshal(YamlEngine.java:50) ~[elasticjob-infra-common-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.shardingsphere.elasticjob.lite.internal.sharding.ShardingService.getCrashedShardingItems(ShardingService.java:185) ~[elasticjob-lite-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.shardingsphere.elasticjob.lite.internal.failover.FailoverListenerManager$JobCrashedJobListener.dataChanged(FailoverListenerManager.java:86) ~[elasticjob-lite-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.shardingsphere.elasticjob.lite.internal.listener.AbstractJobListener.event(AbstractJobListener.java:40) ~[elasticjob-lite-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$null$8(CuratorCacheImpl.java:286) ~[curator-recipes-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.listen.MappingListenerManager.lambda$forEach$0(MappingListenerManager.java:92) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.listen.MappingListenerManager.forEach(MappingListenerManager.java:89) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.listen.StandardListenerManager.forEach(StandardListenerManager.java:89) ~[curator-framework-5.1.0.jar:5.1.0]
	at org.apache.curator.framework.recipes.cache.CuratorCacheImpl.lambda$callListeners$10(CuratorCacheImpl.java:293) ~[curator-recipes-5.1.0.jar:5.1.0]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

**Review by TeslaCN — CHANGES_REQUESTED** [review]
I have some questions about this PR.

**Comment by TeslaCN** [comment]
Hi @sucg 
I've noticed that the testcases failed. Could you fix it?

**Comment by sucg** [comment]
Hi @TeslaCN , I fixed it.

But I find that unit test coverage is reduced, I will analyze the code of the unit test later

And I have a question.
Could you tell me how to deploy it in docker? thank you.

If you have any questions, I am very happy to explain.

**Comment by TeslaCN** [comment]
Hi @sucg
Have you tried the new feature "Run Targets" in IntelliJ IDEA 2021.1? I use this feature to simulate distributed deployment.

**Review by TeslaCN — APPROVED** [review]
Hi@sucg
I did some simple tests and it worked fine! Thanks for your contribution!

**Pull request merged**
