### PR TITLE
solve InetAddress.isReachable() returns incorrectly

### LINKED ISSUE #1858: Elasticjob unable to get local IP address, runtime In JDK version 1.8.0_40
### Which version of ElasticJob did you use?
 - 3.0.0-RC1

### Which project did you use? ElasticJob-Lite or ElasticJob-Cloud?
- ElasticJob-Cloud

### Expected behavior
- Project Launch Successfully

### Actual behavior

> org.apache.shardingsphere.elasticjob.infra.env.HostException: ip is null

	at org.apache.shardingsphere.elasticjob.infra.env.IpUtils.getIp(IpUtils.java:68)

### Reason analyze (If you can)

    Version before jdk1.8.0_74 `InetAddress.isReachable()` returns incorrectly

### Steps to reproduce the behavior.

- JDK 1.8.0_73
- ElasticJob-Cloud 3.0.0-RC1
   `@Test
    public void assertGetIp() {
        assertNotNull(IpUtils.getIp());
    }`

 

> org.apache.shardingsphere.elasticjob.infra.env.HostException: ip is null

	at org.apache.shardingsphere.elasticjob.infra.env.IpUtils.getIp(IpUtils.java:68)
	at org.apache.shardingsphere.elasticjob.infra.env.IpUtilsTest.assertGetIp(IpUtilsTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

### PR DESCRIPTION
**Pull request by lllzh-dev**
Fixes #1858.

Changes proposed in this pull request:
- solve InetAddress.isReachable() returns incorrectly
- use run time ping when InetAddress.isReachable() return false

### CODE REVIEW

**Review by TeslaCN — CHANGES_REQUESTED** [review]
I think using `ping` is not a common way. For example `ping` is not exists in many simplified docker images.

**Comment by lllzh-dev** [comment]
> I think using `ping` is not a common way. For example `ping` is not exists in many simplified docker images.

Ok, I will try some other ways.

**Comment by TeslaCN** [comment]
> > I think using `ping` is not a common way. For example `ping` is not exists in many simplified docker images.
> 
> Ok, I will try some other ways.

It's better to discuss in the issue before coding.

**Comment by lllzh-dev** [comment]
> > > I think using `ping` is not a common way. For example `ping` is not exists in many simplified docker images.
> > 
> > 
> > Ok, I will try some other ways.
> 
> It's better to discuss in the issue before coding.

> > > I think using `ping` is not a common way. For example `ping` is not exists in many simplified docker images.
> > 
> > 
> > Ok, I will try some other ways.
> 
> It's better to discuss in the issue before coding.

Fine, Shoud I move to the issue and discuss some new idea now?

**Comment by sunkai-cai** [comment]
we  may not need `InetAddress.isReachable()` , this is a local network address , `isReachable()` may be always true.

**Comment by TeslaCN** [comment]
Close due to outdated.

**Pull request closed without merging**
